name: test

on:
  workflow_call:

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: pip
      - uses: actions/checkout@v3
      - run: pip3 install -r requirements.txt
      - name: Run tests
        run: coverage run -m unittest discover
